### ISSUE TITLE
no image of the cards back

### ISSUE THREAD

**Issue by Yevgeny-Sh** [crobertsbmw/deckofcards#109]
I'm trying to use the deck-of-cards API for my personal react project,
and I couldn't find a picture of an upside down card (a cards back) - that I can use for my game.
Is there a picture of an upside down card in the deck that I can use?
Any help would be appreciated, thanks!

**Comment by crobertsbmw** [comment]
I made a back image for the card which is found here:
https://deckofcardsapi.com/static/img/back.png

Thanks!

**Comment by cfjedimaster** [comment]
Query - can this be added to the docs? If it's there I didn't see it (100% possibly my fault)

**Comment by crobertsbmw** [comment]
Done. Thanks for the suggestion!
