### ISSUE TITLE
Ace of Diamonds image blocked

### ISSUE THREAD

**Issue by ttse23** [crobertsbmw/deckofcards#116]
Firstly, thank you for making your API available. I'm currently building a card game that utilizes the .png images as part of my UI.

Everything works great, but I've noticed whenever the Ace of Diamonds is drawn, the image fails to load on the DOM. I believe the image URL which contains 'AD' is triggering the ad-blocker extension I have downloaded on my web browser.

I am fairly new to programming so please excuse me if this is a silly question, but is there a simple work-around to this issue?

Thanks in advance!

**Comment by crobertsbmw** [comment]
Instead of ad.png try aceDiamonds.png.

**Comment by ttse23** [comment]
Thank you!
