### ISSUE TITLE
Support discard pile

### ISSUE THREAD

**Issue by swapagarwal** [crobertsbmw/deckofcards#12]

**Comment by TheIronMarx** [comment]
Or at least some manual distinction or states of the cards would be nice. Similar to #10

**Comment by swapagarwal** [comment]
State of a card will only tell that it's discarded. Having a discard pile will keep track of their order.

**Comment by crobertsbmw** [comment]
When should a card hit the discard pile? It doesn't seem right to add a card to the discard pile when the card is drawn. Should there be an api call to add a card to the discard pile? At that point it would be just be an api that would simulate a 'stack'. Is that what we want?

**Comment by crobertsbmw** [comment]
see #10.
