### ISSUE TITLE
Clipboard copy not working

### ISSUE THREAD

**Issue by alcpereira** [crobertsbmw/deckofcards#124]
The [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) works only with secure contexts (HTTPS).

I can implement a small hack to substitute the Clipboard API while the HTTPS isn't operational.
Or do you prefer to focus directly on the SSL certificate?

**Comment by crobertsbmw** [comment]
Interesting. The HTTPS seems to work fine for me. In fact, when I explicitly try to access http://deckofcardsapi.com, it redirects me to the https. Are you still having this problem?
