### ISSUE TITLE
Shuffle a number of negative decks

### ISSUE THREAD

**Issue by Mesquitigor** [crobertsbmw/deckofcards#126]
Like if you try to shuffle -10 decks, the API undertands it like normal and proceed the request normaly and responds 200 OK.
![image](https://user-images.githubusercontent.com/80482870/203169227-82a65f46-143a-4a39-8c8e-b441800e01c8.png)

**Comment by crobertsbmw** [comment]
Oh, that's interesting. What would the intended behaviour here be?

**Comment by Mesquitigor** [comment]
I think that the right behaviour for this case is to respond 400 as status code. Do you agree?

**Comment by chrismahoney** [comment]
The mental image of somebody attempting to somehow shuffle -10 decks is pretty funny though... haha
