### ISSUE TITLE
Drawing cards from the bottom of the deck and at random

### ISSUE THREAD

**Issue by enosunim** [crobertsbmw/deckofcards#135]
They just don't seem to work. And I couldn't find any further documentation on this.

Here's the demonstration I made using Python.
![image](https://github.com/user-attachments/assets/ca6877bf-ae5a-4b4f-8fd5-af11701aabd8)

Any way to fix this?

**Comment by crobertsbmw** [comment]
Looks like there is an error in the docs. /draw/random/ is for drawing cards from piles, so you need to specify a pile name. If you want to just draw from the deck then you call /draw/ without a pile name (if you shuffled the cards, then drawing off the top is just as random as randomly drawing.) I'll update the docs on Monday.

**Comment by enosunim** [comment]
Thanks. Also, is there a way to add cards to the bottom of the deck or a pile? I'm trying to simulate Clock Solitaire with Python using this API.

**Comment by crobertsbmw** [comment]
You can flip the pile upside down, and add cards to the top of the pile, but draw them from the bottom.
