### ISSUE TITLE
Support Non-standard decks

### ISSUE THREAD

**Issue by Gooseus** [crobertsbmw/deckofcards#14]
Pinochle uses a 48 card deck, and Euchre uses a 28 or 32 card deck.

When creating a deck you should also be able to specify the set of cards to include in your deck... using either standard sets or a custom mapping of how many of each standard card you want to include, possibly also with options for "jokers" or "wildcards" that other people have mentioned.

**Comment by swapagarwal** [comment]
Similar to #6
