### ISSUE TITLE
Consider using SVGs for card images?

### ISSUE THREAD

**Issue by voltagex** [crobertsbmw/deckofcards#2]
Posted as a HN comment but thought it might worth an issue -

SVG cards might reduce bandwidth use for you and clients - https://code.google.com/p/vectorized-playing-cards/

For example, 8 of Clubs is:

* 28kb as a PNG.

* 14kb as an SVG (from above set)

* 4kb as a gzipped SVG

**Comment by crobertsbmw** [comment]
Thanks, I will definately look into this tomorrow.

**Comment by crobertsbmw** [comment]
I've been looking at these files. I haven't ever studied up on what SVG's even are until today. All the ones that I have downloaded from the link don't look like they are cropped correctly.

**Comment by voltagex** [comment]
Someone else had this issue - https://shkspr.mobi/blog/2013/03/inkscape-cropping-svg-files-on-the-command-line/

**Comment by golfguru1** [comment]
Maybe have the option of choosing between PNG and SVG? Loading SVGs on iOS is really not fun :P

**Comment by theodorosD** [comment]
+1 for choosing between png and svg! Picaso image loader is a great tool, but useless with svgs.

**Comment by voltagex** [comment]
Using the Accept: header would be a good way of switching between file
types. You could even render PNGs on the fly

**Comment by crobertsbmw** [comment]
Switching on the Accept header is foreign to me.
I don't really like the idea of listing multiple image urls as it just clutters the response. Would there be a way to make both image types available and without returning two image urls in the response?
I am starting to wonder if it would be easier to just switch back to PNG?

**Comment by golfguru1** [comment]
Back to PNG! (Unless thats going to upset more people than it will please...)

**Comment by voltagex** [comment]
Switching on the Accept: header would be the "RESTful" thing to do, you
could also use the file extension or a &format= parameter.

...or go back to PNG :P

**Comment by crobertsbmw** [comment]
I moved the default to PNG for now..
When I say it's foreign to me, what I mean is that I have no idea how to do it. What parameter should I look for in the accept header?

**Comment by voltagex** [comment]
You'd look for a MIME type in the header, so the client would ask for
image/png or image/svg+xml

**Comment by theodorosD** [comment]
Thanks for the PNG support!
