### ISSUE TITLE
Consider using deck size

### ISSUE THREAD

**Issue by vladegikyan** [crobertsbmw/deckofcards#21]
Hello,
I am looking for such API as yours and I have an idea of a game.
Though, there are games that use less then 52 cards in the deck.
I think that it will be reasonable to add maybe optional deck_size parameter to /deck/new/

**Comment by crobertsbmw** [comment]
This issue has already been address. See this: http://deckofcardsapi.com/#partial-deck

**Comment by vladegikyan** [comment]
Yes, but it is not usable at all to pass 36 or 32 cards. Why not to pass
just number?

**Comment by crobertsbmw** [comment]
So which ones would the api remove? Do you want a deck of 32 random cards?
If that's the case, you could just draw 4 cards and then ignore them.
