### ISSUE TITLE
Fix the url in Partial Deck API documention

### ISSUE THREAD

**Issue by rupakg** [crobertsbmw/deckofcards#24]
Fix this:
A Partial Deck:
http://deckofcardsapi.com/api/deck/shuffle/?cards=AS,2S,KS,AD,2D,KD,AC,2C,KC,AH,2H,KH

to

A Partial Deck:
http://deckofcardsapi.com/api/deck/<<deck_id>>shuffle/?cards=AS,2S,KS,AD,2D,KD,AC,2C,KC,AH,2H,KH

Nice API!

**Comment by crobertsbmw** [comment]
I'm a little confused. Why the "<>shuffle"?

**Comment by crobertsbmw** [comment]
Nevermind, I see what you are saying. I've updated the documentation. Thanks for catching it.

**Comment by rupakg** [comment]
@crobertsbmw github comments took out my part where I intented to say 'deck_id'. But, glad you got it. Thanks.
