### ISSUE TITLE
Bug in Piles?

### ISSUE THREAD

**Issue by chrisjstevenson** [crobertsbmw/deckofcards#25]
I'm trying to add a card to pile...

Request:  http://deckofcardsapi.com/api/deck/rt3ge4ytwfew/pile/discard/add/?cards=2S,KS

Response:  {"remaining": 52, "deck_id": "rt3ge4ytwfew", "success": true, "piles": {"discard": {"remaining": 0}}}

Should "remaining" be 2 and not 0?

**Comment by crobertsbmw** [comment]
Thanks for checking out the API. I think the problem is that you first have
to draw the card from the deck before you can add it to a pile. If that
doesn't work, let me know and I can look into it further.

**Comment by chrisjstevenson** [comment]
Yep, that works, thanks!
