### ISSUE TITLE
Reshuffling partial deck yields new, full, deck

### ISSUE THREAD

**Issue by therealgregvernon** [crobertsbmw/deckofcards#26]
After creating a partial deck using the request /api/<deck id>/shuffle will result in a new, 52 card, deck.

**Comment by rcopley** [comment]
I'm wondering the best way to solve this. When a partial deck is made, there's nothing keeping track of *which* cards are put in the partial deck.

I'm thinking the best way to fix it would be to add a ```deckContents``` property to the deck which tracks the cards originally used in a partial deck. Maybe make the assumption that if the list is empty a full deck is assumed (to prevent doubling the amount of memory needed for regular full decks).

**Comment by rcopley** [comment]
I think this issue can be closed. The two commits above have been merged to Master and they fix the odd behavior @therealgregvernon mentioned.
