### ISSUE TITLE
piles -- "add" is really "create"?

### ISSUE THREAD

**Issue by mansilladev** [crobertsbmw/deckofcards#30]
Lets say I've added 3 cards to a pile earlier, and now call ```/deck/{deckid}/pile/{pilename}/add``` again, but with a single freshly drawn card from the deck -- ```{pilename}``` really just gets overwritten with that single new card, correct?

**Comment by crobertsbmw** [comment]
I don't think so. If you call `/add/` again, then it should just add to the pile, not overwrite it.

**Comment by mansilladev** [comment]
Hmm. Give it a whirl and let me see if you're experiencing the same thing. On a new deck, I discard a couple cards. Add a single one to new pile "foo" and there's one in the pile. Add another single one to pile, and there's just that one in the pile.

**Comment by crobertsbmw** [comment]
You're right. Good catch. Give me a few minutes and it'll be fixed.

**Comment by crobertsbmw** [comment]
Try it now. It should be fixed. Thanks for bringing this up. I'm surprised that no one has reported it until now.

**Comment by mansilladev** [comment]
Thanks Chase. I'm using DeckOfCards in a Skillshare course for API testing, so I'm diving in a bit deeper than most, most likely. :)

**Comment by crobertsbmw** [comment]
No, thank you.
If you have a link or a write up or some way to share what you are using it
for, I would love to feature it on the main page.
