### ISSUE TITLE
Demo API Server is down

### ISSUE THREAD

**Issue by terry81811** [crobertsbmw/deckofcards#31]
Demo API Server(http://deckofcardsapi.com/api/deck/) is down with HTTP 500 response.

**Comment by crobertsbmw** [comment]
You need to specify what you want to do with the deck:

open a new deck:
http://deckofcardsapi.com/api/deck/new/

open and shuffle a new deck:
http://deckofcardsapi.com/api/deck/new/shuffle/

see http://deckofcardsapi.com/ for more examples.

**Comment by terry81811** [comment]
Thank you for replying.
But I did go through the document and built sth upon your demo api. It was working fine 10 hours ago but not now. And the two addresses you provided are returning 500 as well.

**Comment by crobertsbmw** [comment]
Thanks for bringing this up. When you initially opened the issue, I wasn't getting this problem, but now I am. Apparently, my Amazon Micro instance completely filled up, so there was no more space for saving new decks. I had to pretty much purge the entire database, but it's back online now. 

Thanks again.
