### ISSUE TITLE
How to shuffle pile or draw card from bottom of pile?

### ISSUE THREAD

**Issue by jmiller-io** [crobertsbmw/deckofcards#36]
Really digging this API. Thanks for all this.

Quick question.
How do you go about drawing a card from the bottom of a pile or shuffling the cards in a pile? I can't find any documentation for that.

I've tried this:
https://deckofcardsapi.com/api/deck/<<deck_id>>/pile/<<pile_name>>/shuffle/
https://deckofcardsapi.com/api/deck/<<deck_id>>/pile/<<pile_name>>/draw/bottom

Thank you.
-Jake

**Comment by crobertsbmw** [comment]
Jake,
Thanks! I'm glad you like it.
Currently, you can only draw from the top of the stack or pick out the
specific card you want. If you want to submit a PR, I would be happy to
review it and include it in the api.
It can be added to the views.py file (
https://github.com/crobertsbmw/deckofcards/blob/master/deck/views.py) and
the method could be called "def shuffle_pile(request, pile_name):"
I would add this myself, but work and family are eating up all my time
right now, so the api doesn't get as much time as I would like.

Best,
-Chase
Also, I would love to hear (or see) anything that you build with it.

**Comment by jmiller-io** [comment]
Hey Chase,

Thanks for the quick response. Got ya. What I ended up doing was make an initial call to the API for a deck  and then just split and store the user piles in local variables. I haven't worked with Python but have been wanting to learn. This is a good opportunity. I forked the repo and plan on digging in and seeing if I can do that. I'm just making a very simple JS War game.

-Jake

**Comment by crobertsbmw** [comment]
Sounds awesome. Let me know when you are done with it. I would love to see
it.

Best,
Chase
