### ISSUE TITLE
Error behavior for empty decks / counts that are too large

### ISSUE THREAD

**Issue by pcottle** [crobertsbmw/deckofcards#4]
Copying from HN:

Pretty cool! Love that theres no authentication and I can start straight from curl.

Nit: drawing from an empty deck does not throw an error:
```
> curl http://deckofcardsapi.com/api/draw/i763hn8lcg0e/ 
{"remaining": 0, "cards": [], "deck_id": "i763hn8lcg0e", "success": true}
```

As does drawing a comically large number of cards:
```
> curl http://deckofcardsapi.com/api/draw/vzlem7q4jhna/?count=10000
... (...) "success": true}\n
```

i think both of these should throw errors, or at least return `success: false`. thoughts?

**Comment by crobertsbmw** [comment]
Thanks for the feedback. I agree with you on all these points. I'll work on a fix for these.
