### ISSUE TITLE
Should not be able to add cards to multiple piles

### ISSUE THREAD

**Issue by LukeHowellDev** [crobertsbmw/deckofcards#41]
Currently, you can add a card to multiple piles. This should not be allowed. This can be replicated like the following:

1. Create new deck
1. Draw a number of cards from the deck
1. Add a card to `pile1`
1. Add the same card to `pile2`

You will see the card in both piles using `api/deck/<<deck_id>>/pile/<<pile_name>>/list

**Comment by LukeHowellDev** [comment]
I'll probably submit a PR for this in a day or so.

**Comment by piavgh** [comment]
Hi @LukeHowellDev ,

I noticed this issue too. Do you have a plan to work on it?
Thank you.

**Comment by crobertsbmw** [comment]
I'll check it out today. Thanks for the reminder.

**Comment by crobertsbmw** [comment]
Fixed.
