### ISSUE TITLE
Should be able to list cards not in any pile

### ISSUE THREAD

**Issue by LukeHowellDev** [crobertsbmw/deckofcards#42]
When cards are drawn they are not in any pile (`deck.stack` or created pile). If the list of cards in `no man's land` could be listed this could help with placing certain cards. This would also be beneficial for restoring application state at a later time.

This could also, be useful in solving #41. If there is a way to list drawn cards that are in no pile then a case can be made that only drawn cards can be placed into a pile.

Another bonus is that this may bring the ability to add and manipulate piles to cases when multiple decks are being used.

**Comment by LukeHowellDev** [comment]
I'll probably submit a PR for this in a day or so.

**Comment by LukeHowellDev** [comment]
@crobertsbmw Is this something you would be interested in before I start work on it?

**Comment by crobertsbmw** [comment]
Sure! I'm not actively doing anything with the project so it doesn't see new features very often. But I'm open to new pull requests. 
So the api call would list all the cards that have been drawn that haven't been put in a pile? Or would it just list all the cards in the deck?

**Comment by LukeHowellDev** [comment]
My thought was that it would list all cards that have been drawn from the deck, but that are not in any pile.

**Comment by LukeHowellDev** [comment]
My thought was that it would list all cards that have been drawn from the deck, but that are not in any pile.

**Comment by crobertsbmw** [comment]
Sounds good.

**Comment by R4N4R4M4** [comment]
Hi, this API is really cool. Is it possible to add a picture, or many, for the back of cards ?
