### ISSUE TITLE
Server error: 500

### ISSUE THREAD

**Issue by DASADASbs** [crobertsbmw/deckofcards#48]
Failed to load https://deckofcardsapi.com/api/deck/ibnhgqxo0lxn/draw/?count=undefined: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://palmpa76.beget.tech' is therefore not allowed access. The response had HTTP status code 500.

GET https://deckofcardsapi.com/api/deck/ibnhgqxo0lxn/draw/?count=undefined 500 ()

**Comment by crobertsbmw** [comment]
You can't draw an `undefined` number of cards:
https://deckofcardsapi.com/api/deck/ibnhgqxo0lxn/draw/?count=**undefined**
