### ISSUE TITLE
Consider using a CSPRNG

### ISSUE THREAD

**Issue by Spaceghost** [crobertsbmw/deckofcards#5]
I'd suggest you change your random function.

I'm not a pythonist myself, but something that seeds from urandom would be better. https://docs.python.org/3/library/os.html#os.urandom

**Comment by crobertsbmw** [comment]
I will look into urandom. I was almost thinking it would be cool to implement a simulation of a riffle shuffle (http://en.wikipedia.org/wiki/Shuffling#Riffle). Although randomness would still be just as valid of an issue and the end user probably wouldn't ever care or even know.
