### ISSUE TITLE
CORS settings

### ISSUE THREAD

**Issue by donbraffitt** [crobertsbmw/deckofcards#54]
Hi,

I was trying to load a card image in JavaScript, but I think the CORS headers on your web server do not allow this.

Here are 2 .png files I tried:

https://raw.githubusercontent.com/petercpark/Mindless-Rubik-s-Cube-Solution/master/rubikscube.png
https://deckofcardsapi.com/static/img/KH.png

The 1st loads fine from JavaScript, but the 2nd fails when I try to load it from JavaScript. Here is the URL I used to test CORS headers for these 2 .png files:

https://www.test-cors.org/

I just pasted each URL into the Remote URL box. The JavaScript framework I am using is p5.js, but I don't think the framework is the source of this particular problem since the CORS headers test fine for the rubikscube.png file and that file loads fine in p5.js, but the KH.png file fails the CORS headers test and will not load in p5.js using loadImage.

Don Braffitt

**Comment by crobertsbmw** [comment]
So I added a cors headers to the server. And it seems to be working:

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fdeckofcardsapi.com%2Fstatic%2Fimg%2F5H.png&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by donbraffitt** [comment]
Yes. I can now load the card images from p5.js using loadImage(). Thanks!

Don
