### ISSUE TITLE
CORS problema

### ISSUE THREAD

**Issue by gabrigcl** [crobertsbmw/deckofcards#57]
Hi. I think the CORS headers on your web server do not allow me to use the API. I'm trying to use https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1 and https://deckofcardsapi.com/api/deck/<<deck_id>>/draw/?count=2 endpoints. 

Please help me, I'm working in a job test and depending on this issue.

**Comment by crobertsbmw** [comment]
Yeah, I think you might be right. In the meantime, you should be able to make a `GET` request instead of a `POST`:
```
var http = new XMLHttpRequest();
var url = 'https://deckofcardsapi.com/api/deck/new/shuffle/';
var params = 'deck_count=1';
http.open('GET', url, true);

http.onreadystatechange = function() {//Call a function when the state changes.
    if(http.readyState == 4 && http.status == 200) {
        alert(http.responseText);
    }
}
http.send(params);
```

**Comment by gabrigcl** [comment]
But I'm mailing GET requests, It doesn't work

**Comment by crobertsbmw** [comment]
Can you post some example code of what you’re doing? When I try it in vanilla JavaScript with the code above in a browser console, then it works fine for me.

**Comment by gabrigcl** [comment]
I'm using a localhost server from an Angular app. I think your server doesn't send 'Access-control-allow-origin' header to enable all origins to use your endpoints, and because of this, the default behavior of the browsers is to block access.

**Comment by gabrigcl** [comment]
I've already resolved this issue, I'm now using a Proxy in the Angular development server and now It works.
