### ISSUE TITLE
Not able to list piles.

### ISSUE THREAD

**Issue by prichieri** [crobertsbmw/deckofcards#59]
When I try to list a pile I get this error.

"The requested URL /api/deck/0cwtkus4fju6/pile/Jugador1/list was not found on this server."

Can enyone tell me how to solve it?

Thanks.

**Comment by crobertsbmw** [comment]
You aren't doing anything wrong. It seems there is a bug somewhere. I'll
try to get it sorted out soon. Thanks for the tip.

-Chase

**Comment by prichieri** [comment]
Great, thanks Chase!!! By the way, thaks for the API. Is great for starters like myself

**Comment by crobertsbmw** [comment]
Okay, so it seems the problem is that you need a trailing slash at the end:
`/api/deck/0cwtkus4fju6/pile/Jugador1/list` needs to be:
`/api/deck/0cwtkus4fju6/pile/Jugador1/list/`
And then it should work. I'll update the docs, and look into automatically adding the trailing slash. Thanks.

**Comment by prichieri** [comment]
Thank you Chase!!!
