### ISSUE TITLE
Support different CARDS

### ISSUE THREAD

**Issue by ZeissS** [crobertsbmw/deckofcards#6]
In Germany we have a bunch of card games which require only a subset of the normal card decks:
 * Doppelkopf (9, 10, J, Q, K, A, but two of those decks)
 * Skat (7-10, J, Q, K, A)

It would be nice to support having a subset of the cards

**Comment by neuhaus** [comment]
I second this request.
There are some details at https://en.wikipedia.org/wiki/German_playing_cards

**Comment by rahulgr8888** [comment]
Even here in India, there are many games that require stripped decks like this one-
```
https://en.wikipedia.org/wiki/3-2-5#Cards
```
> The game is played with a 30-card stripped deck limited to all 8s onwards for all suits except for the 7 of Hearts and the 7 of Spades.

So, there should be some way to make a stripped deck too!

**Comment by MattyDub** [comment]
In games played in the US as well, subsets of the 54-card (counting Jokers) deck are used. See Euchre (http://en.wikipedia.org/wiki/Euchre) or Pinochle (http://en.wikipedia.org/wiki/Pinochle).

**Comment by jlzavitz** [comment]
+1

**Comment by crobertsbmw** [comment]
Thanks to jlzavitz for taking care of this for me.

**Comment by crobertsbmw** [comment]
I'm sorry, that was supposed to say thanks to foxbenjaminfox. 

Thanks to jlzavitz for keeping me honest.
