### ISSUE TITLE
Internal Server Error 500 when adding cards to pile.

### ISSUE THREAD

**Issue by jambis** [crobertsbmw/deckofcards#63]
Hello, lately with the new changes I haven't been able to add cards to a pile after drawing them.

I have a partial deck with 21 cards, I draw all 21 cards from the deck and then try to add them to a pile and this is when I get an internal server error 500.

This process was working before the changes. I was wondering if there's something on my end that I should be changing to make this work again?

**Comment by crobertsbmw** [comment]
Thanks for letting me know. It looks like I broke something yesterday. I
think I have it fixed now, go ahead and try it again.

Thanks,
Chase

**Comment by jambis** [comment]
Awesome Chase, works perfectly now. Thank you
