### ISSUE TITLE
Any chance you have the image for the back of a card?

### ISSUE THREAD

**Issue by markalanevans** [crobertsbmw/deckofcards#64]

**Comment by crobertsbmw** [comment]
No, the images were borrowed from Wikipedia. 
https://en.wikipedia.org/wiki/Standard_52-card_deck#Rank_and_color

And they don't have have an image of the back unfortunately.

**Comment by Danny-Engelman** [comment]
If you target modern browsers supporting Custom Elements,  
you can use the SVG playingcard images from https://cardmeister.github.io

**Comment by chriseickemeyerGH** [comment]
There's a few non-conventional backs to use on wikimedia commons => https://commons.wikimedia.org/wiki/Playing_card
