### ISSUE TITLE
Piles should have to be clear when the deck is shuffled

### ISSUE THREAD

**Issue by Antoine-Turostowski** [crobertsbmw/deckofcards#65]
Hello !
Apologize in advance for writing, i'm french !

When a deck is shuffled, all his cards come back in it, 
but piles are not cleared, so we can have duplicated cards in both deck and pile
is it normal ?

Thank you !

**Comment by crobertsbmw** [comment]
Alright. I think I got this fixed. Thanks for your help!

**Comment by Antoine-Turostowski** [comment]
Perfect, it works !
