### ISSUE TITLE
Shuffle appears to be broken

### ISSUE THREAD

**Issue by paulzim** [crobertsbmw/deckofcards#67]
Using this script for a demo, the API calls worked fine for new decks and card draws, but got an error each time we tried to run shuffle. 

Getting this error:
bash: https://deckofcardsapi.com/api/deck/yacpsah3sxzx/shuffle/: No such file or directory

**Comment by crobertsbmw** [comment]
I copied and pasted the url into the browser and it seems to work fine for me.
<img width="726" alt="Screen Shot 2020-01-30 at 2 32 51 PM" src="https://user-images.githubusercontent.com/5834142/73458664-8af48b80-436d-11ea-87c7-4f9348a89c55.png">
Is there something else going on in your implementation?
