### ISSUE TITLE
Getting an error 500 

### ISSUE THREAD

**Issue by AnuradhaSivasubramanian** [crobertsbmw/deckofcards#70]
We are using your API for a webApp and it seems like any request is sending us an error 500. Could you please help us, we are bootcamp trainees with our Demo day in 4 days.

**Comment by crobertsbmw** [comment]
Sorry. The server ran out of space. I've deleted all the log files and it's
back online now. Thanks for the heads up.

Best,
Chase

**Comment by AnuradhaSivasubramanian** [comment]
Thank you Chanse. Much appreciated.
