### ISSUE TITLE
hide cards from other player

### ISSUE THREAD

**Issue by peterdri** [crobertsbmw/deckofcards#72]
For a two player game, how do you see your own cards, but hide them from the other player?

**Comment by peterdri** [comment]
In other words, after dealing the cards, how can I look at my cards without the other player able to look at them?

**Comment by crobertsbmw** [comment]
That needs to happen on the frontend. The api doesn't show or hide cards;
it just manages the deck.
If you are creating a game with two players (on different computers, rather
than standing next to eachother on the same computer), you will need a
server. The server could make calls to deckofcardsapi, and could then send
messages back to the client with which cards they have and handle all the
game logic.
