### ISSUE TITLE
Unable to fetch image for 10's via https://deckofcardsapi.com/static/img/10H.png or any other suit

### ISSUE THREAD

**Issue by gberg1** [crobertsbmw/deckofcards#75]
Hi thanks for the great api. I've been able to fetch all the images for the cards except for the number 10. I get a 404 error for every suit but am using the same api url as for the other cards such as 

https://deckofcardsapi.com/static/img/10H.png
https://deckofcardsapi.com/static/img/10C.png
https://deckofcardsapi.com/static/img/10S.png
https://deckofcardsapi.com/static/img/10D.png

Please advise! These seem to be the only images missing.

**Comment by crobertsbmw** [comment]
Instead of 10H.png try 0H.png

**Comment by gberg1** [comment]
Thanks
