### ISSUE TITLE
Images for Jokers

### ISSUE THREAD

**Issue by donbraffitt** [crobertsbmw/deckofcards#77]
The .png and .svg files for the Jokers do not exist:

52	
code	"X1"
image	"https://deckofcardsapi.com/static/img/X1.png"
images	
svg	"https://deckofcardsapi.com/static/img/X1.svg"
png	"https://deckofcardsapi.com/static/img/X1.png"
value	"JOKER"
suit	"BLACK"
53	
code	"X2"
image	"https://deckofcardsapi.com/static/img/X2.png"
images	
svg	"https://deckofcardsapi.com/static/img/X2.svg"
png	"https://deckofcardsapi.com/static/img/X2.png"
value	"JOKER"
suit	"RED"

This issue for me is very low priority. I was just trying out various options in the API.

**Comment by crobertsbmw** [comment]
I had them named XX.png and XX.jpg. I renamed them, and they should be loading now; although the SVG version isn't very pretty.
