### ISSUE TITLE
Images for card reverse?

### ISSUE THREAD

**Issue by donbraffitt** [crobertsbmw/deckofcards#78]
Do you by chance have any images for the reverse side of cards? I realize you don't have anything for this in the API, but what I want to display is a card face down. My plan is just to start with one of your .png or .svg files for sizing unless you already have done this.

**Comment by crobertsbmw** [comment]
There's a few non-conventional backs to use on wikimedia commons => https://commons.wikimedia.org/wiki/Playing_card

But, I've had this request a few times. If you want to design a card backing. I am happy to link to it in the docks ;)
