### ISSUE TITLE
aceDiamonds.svg?

### ISSUE THREAD

**Issue by donbraffitt** [crobertsbmw/deckofcards#79]
Should the file aceDiamonds.svg exist? I was experimenting today with the .svg variants of the card images.

13	
code	"AD"
image	"https://deckofcardsapi.com/static/img/aceDiamonds.png"
images	
svg	"https://deckofcardsapi.com/static/img/AD.svg"
png	"https://deckofcardsapi.com/static/img/AD.png"
value	"ACE"
suit	"DIAMONDS"

**Comment by crobertsbmw** [comment]
I don't see why it shouldn't! I just added it. Someone pointed out that their adblocker didn't like the filename AD.png, so that's why it was renamed to aceDiamonds.
