### ISSUE TITLE
Server Error 500 when adding cards to pile

### ISSUE THREAD

**Issue by rjquiban** [crobertsbmw/deckofcards#87]
I get a server error 500 when I try adding cards to a pile. I draw the cards initially before attempting to add the cards to the pile. 
<img width="562" alt="Screen Shot 2020-08-27 at 1 33 29 PM" src="https://user-images.githubusercontent.com/52214808/91492110-ec2fff00-e869-11ea-91f2-bdbe9032ed2f.png">

**Comment by crobertsbmw** [comment]
Thanks for reporting this! I think I fixed the issue. Go ahead and try it now and let me know if you run into any other problems.

Thanks!
