### ISSUE TITLE
Error 500 when shuffling non-existent deck_id

### ISSUE THREAD

**Issue by xsrpm** [crobertsbmw/deckofcards#91]
Hi, I love this API. I am testing it and I found that the api returns error 500 when a non-existent deck_id is passed to it, I suppose this could happen if a deck is deleted, but I forced the case by giving an id that did not exist. It seems to me that the api could give a more consistent error. Good job!

![imagen](https://user-images.githubusercontent.com/7269247/100242090-66702e00-2f02-11eb-978c-835385bf702a.png)

**Comment by crobertsbmw** [comment]
Thanks for bringing this to my attention. I actually was calling the method
"deck_id_does_not_exist()", but I wasn't returning the response. An easy
fix, I just needed to add "return deck_id_does_not_exist()". It should be
online and working now!

**Comment by xsrpm** [comment]
![imagen](https://user-images.githubusercontent.com/7269247/100288869-a573a300-2f45-11eb-9102-8e2bfd1e1c08.png)

Closed
