### ISSUE TITLE
add copy button on the website to copy the links 

### ISSUE THREAD

**Issue by withrvr** [crobertsbmw/deckofcards#97]
# copy button in front of the links

add copy button on the website to copy the links of the API
so the speed increases while working on projects

**Comment by crobertsbmw** [comment]
oh, that's a great idea!

**Comment by StephenBuley** [comment]
Hey @crobertsbmw, I am relatively new to coding and I have never done the Open Source thing before, but I'd like to give this a shot. I feel like I understand the general process, but I'm not sure what specifically YOU want the process to be.  I've already forked the repository and written my code, but I'm not sure what to do from here for you to see if it's ok.  Let me know! Thanks.

**Comment by crobertsbmw** [comment]
Perfect. If you go to github, there should be an option somewhere to submit
a Pull Request.

https://opensource.com/life/16/3/submit-github-pull-request

I'll review the code, and if it looks good then I'll merge it into the main
repository. Thanks for your help!
